globalThis.SEARCH_SHORTCODES = {
    g: { url: "www.google.com/search?q=", desc: "Google" },
    gm: {
        url: "www.google.com/maps/search/",
        base: "google.com/maps",
        desc: "Google Maps",
    },
    gt: { url: "trends.google.com/explore?q=", desc: "Google Trends" },
    yt: { url: "www.youtube.com/search?q=", desc: "YouTube" },
    appm: { url: "music.apple.com/search?term=", desc: "Apple Music" },
    b: { url: "www.bing.com/search?q=", desc: "Bing Search" },
    ddg: { url: "start.duckduckgo.com/?q=", desc: "DuckDuckGo" },
    ddgh: { url: "html.duckduckgo.com/html?q=", desc: "DuckDuckGo (HTML)" },
    ddgl: { url: "lite.duckduckgo.com/lite?q=", desc: "DuckDuckGo (Lite)" },
    yan: { url: "yandex.com/search/?text=", desc: "Yandex" },
    y: { url: "search.yahoo.com/search?p=", desc: "Yahoo!" },
    ask: { url: "www.ask.com/web?q=", desc: "Ask" },
    q: { url: "www.qwant.com/?q=", desc: "Qwant" },
    sp: { url: "www.startpage.com/do/search?query=", desc: "StartPage" },
    br: { url: "search.brave.com/search?q=", desc: "Brave Search" },
    eco: { url: "www.ecosia.org/search?q=", desc: "Ecosia" },
    amz: { url: "www.amazon.co.uk/s?k=", desc: "Amazon" },
    hn: {
        url: "hn.algolia.com/?q=",
        base: "news.ycombinator.com",
        desc: "Hacker News",
    },
    w: { url: "wikipedia.org/w/index.php?search=", desc: "Wikipedia" },
    ud: {
        url: "www.urbandictionary.com/define.php?term=",
        desc: "Urban Dictionary",
    },
    r: { url: "www.reddit.com/search/?q=", desc: "Reddit" },
    ciu: { url: "caniuse.com/?search=", desc: "Can I Use" },
    imdb: { url: "www.imdb.com/find/?q=", desc: "IMDB" },
    osm: { url: "www.openstreetmap.org/search?query=", desc: "OpenStreetMap" },
    mdn: { url: "developer.mozilla.org/en-US/search?q=", desc: "MDN Web Docs" },
    html: {
        url: "developer.mozilla.org/en-US/search?topic=html&q=",
        base: "developer.mozilla.org/en-US/docs/Web/HTML",
        desc: "MDN HTML",
    },
    css: {
        url: "developer.mozilla.org/en-US/search?topic=css&q=",
        base: "developer.mozilla.org/en-US/docs/Web/CSS",
        desc: "MDN CSS",
    },
    js: {
        url: "developer.mozilla.org/en-US/search?topic=js&q=",
        base: "developer.mozilla.org/en-US/docs/Web/JavaScript",
        desc: "MDN JavaScript",
    },
    cfd: {
        url: "developer.chrome.com/s/results?q=",
        desc: "Chrome for Developers",
    },
    pypi: { url: "pypi.org/search/?q=", desc: "Python Package Index" },
    bs: { url: "bsky.app/search?q=", desc: "Bluesky" },
    gh: { url: "github.com/search?q=", desc: "GitHub" },
    mcw: { url: "minecraft.wiki/w/?search=", desc: "Minecraft Wiki" },
    sms: { url: "searchmysite.net/search/?q=", desc: "Search My Site" },
    s: { url: "www.shodan.io/search?query=", desc: "Shodan" },
    apple: { url: "www.apple.com/search/", desc: "Apple" },
    v: { url: "www.theverge.com/search?q=", desc: "The Verge" },
};
